model 1.1 artifact
ihmeuw/vivarium_gates_nutrition_optimization_child pull request #12
Opened 2023-08-23 20:25 UTC by hussain-jafari

## model 1.1 artifact

### Description
- *Category*: artifact
- *JIRA issue*: [MIC-4407](https://jira.ihme.washington.edu/browse/MIC-4407)
- *Research reference*: [supplementation effect on gestational age](https://vivarium-research.readthedocs.io/en/latest/models/intervention_models/maternal_supplementation/index.html#id49)

### Changes and notes
Update data_keys to include gestational age exposure in LBWSG and write new MMN_SUPPLEMENTATION key which no longer fits the other additive risk key patterns. 
Add shift data from RT.
Update IFA excess shift to include gestational age exposure and write two new keys for the MMS excess shift for the two subpopulations it effects. 

### Verification and Testing
Generated new artifact and ran sim with artifact data.

2023-08-23 21:35 UTC, albrja approved these changes

2023-08-23 23:39 UTC, rmudambi requested changes

2023-08-23 23:39 UTC, rmudambi commented on src/vivarium_gates_nutrition_optimization_child/data/loader.py
>      location: str, distribution_data: Tuple, is_risk: bool
You are not using the `is_risk` value anywhere anymore. Is it always False? If so, you should remove the parameter entirely. If it is not always False, then you've introduced a bug here.

2023-08-24 20:26 UTC, rmudambi approved these changes

2023-08-24 20:28 UTC, merged